//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeYak
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLLOWING
    {
        public string FOLLOWING_ID { get; set; }
        public string FOLLOWING_UN { get; set; }
        public string FOLLOWER_UN { get; set; }
        public Nullable<System.DateTime> DATE_STARTED { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
        public virtual MEMBER MEMBER1 { get; set; }
    }
}
