//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeYak
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALERT> ALERTs { get; set; }
        public virtual DbSet<COLLEGE> COLLEGEs { get; set; }
        public virtual DbSet<FOLLOWING> FOLLOWINGs { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<POST> POSTs { get; set; }
        public virtual DbSet<REPORT> REPORTs { get; set; }
        public virtual DbSet<VOTE> VOTEs { get; set; }
        public virtual DbSet<POST_VIEW> POST_VIEW { get; set; }
        public virtual DbSet<VOTEDOWN_VIEW> VOTEDOWN_VIEW { get; set; }
        public virtual DbSet<VOTEUP_VIEW> VOTEUP_VIEW { get; set; }
    
        public virtual int CHECKVOTE(string vOTETYPE, string vOTER_USERNAME, string vOTED_USERNAME, Nullable<decimal> pOSTID)
        {
            var vOTETYPEParameter = vOTETYPE != null ?
                new ObjectParameter("VOTETYPE", vOTETYPE) :
                new ObjectParameter("VOTETYPE", typeof(string));
    
            var vOTER_USERNAMEParameter = vOTER_USERNAME != null ?
                new ObjectParameter("VOTER_USERNAME", vOTER_USERNAME) :
                new ObjectParameter("VOTER_USERNAME", typeof(string));
    
            var vOTED_USERNAMEParameter = vOTED_USERNAME != null ?
                new ObjectParameter("VOTED_USERNAME", vOTED_USERNAME) :
                new ObjectParameter("VOTED_USERNAME", typeof(string));
    
            var pOSTIDParameter = pOSTID.HasValue ?
                new ObjectParameter("POSTID", pOSTID) :
                new ObjectParameter("POSTID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CHECKVOTE", vOTETYPEParameter, vOTER_USERNAMEParameter, vOTED_USERNAMEParameter, pOSTIDParameter);
        }
    
        public virtual int CHECKVOTEGEAROID(string vOTETYPE, string vOTER_USERNAME, string vOTED_USERNAME, Nullable<decimal> pOSTID)
        {
            var vOTETYPEParameter = vOTETYPE != null ?
                new ObjectParameter("VOTETYPE", vOTETYPE) :
                new ObjectParameter("VOTETYPE", typeof(string));
    
            var vOTER_USERNAMEParameter = vOTER_USERNAME != null ?
                new ObjectParameter("VOTER_USERNAME", vOTER_USERNAME) :
                new ObjectParameter("VOTER_USERNAME", typeof(string));
    
            var vOTED_USERNAMEParameter = vOTED_USERNAME != null ?
                new ObjectParameter("VOTED_USERNAME", vOTED_USERNAME) :
                new ObjectParameter("VOTED_USERNAME", typeof(string));
    
            var pOSTIDParameter = pOSTID.HasValue ?
                new ObjectParameter("POSTID", pOSTID) :
                new ObjectParameter("POSTID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CHECKVOTEGEAROID", vOTETYPEParameter, vOTER_USERNAMEParameter, vOTED_USERNAMEParameter, pOSTIDParameter);
        }
    
        public virtual int CREATEPOST(string dETAILS, Nullable<decimal> iD)
        {
            var dETAILSParameter = dETAILS != null ?
                new ObjectParameter("DETAILS", dETAILS) :
                new ObjectParameter("DETAILS", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATEPOST", dETAILSParameter, iDParameter);
        }
    
        public virtual int LIST_VOTERS_FOR_POST(Nullable<decimal> v_POST_ID)
        {
            var v_POST_IDParameter = v_POST_ID.HasValue ?
                new ObjectParameter("V_POST_ID", v_POST_ID) :
                new ObjectParameter("V_POST_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LIST_VOTERS_FOR_POST", v_POST_IDParameter);
        }
    
        public virtual int LOGGINGIN(string uNAME, string pSW)
        {
            var uNAMEParameter = uNAME != null ?
                new ObjectParameter("UNAME", uNAME) :
                new ObjectParameter("UNAME", typeof(string));
    
            var pSWParameter = pSW != null ?
                new ObjectParameter("PSW", pSW) :
                new ObjectParameter("PSW", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOGGINGIN", uNAMEParameter, pSWParameter);
        }
    
        public virtual int SIGNIN(string nAME, string eMAIL, string cOLLEGE, string pASSWORD, Nullable<decimal> aGE)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var cOLLEGEParameter = cOLLEGE != null ?
                new ObjectParameter("COLLEGE", cOLLEGE) :
                new ObjectParameter("COLLEGE", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var aGEParameter = aGE.HasValue ?
                new ObjectParameter("AGE", aGE) :
                new ObjectParameter("AGE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SIGNIN", nAMEParameter, eMAILParameter, cOLLEGEParameter, pASSWORDParameter, aGEParameter);
        }
    }
}
