//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeYak
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST_VIEW
    {
        public string Username { get; set; }
        public string DETAILS { get; set; }
        public Nullable<System.DateTime> POST_TIME { get; set; }
        public decimal POST_ID { get; set; }
    }
}
