//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeYak
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POST()
        {
            this.ALERTs = new HashSet<ALERT>();
            this.VOTEs = new HashSet<VOTE>();
        }
    
        public decimal POST_ID { get; set; }
        public string COLLEGE_NAME { get; set; }
        public string USERNAME_OP { get; set; }
        public string DETAILS { get; set; }
        public Nullable<System.DateTime> POST_TIME { get; set; }
        public string VISIBILITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALERT> ALERTs { get; set; }
        public virtual COLLEGE COLLEGE { get; set; }
        public virtual MEMBER MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOTE> VOTEs { get; set; }
    }
}
