//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeYak
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public decimal REPORT_ID { get; set; }
        public string USERNAME_REPORTER { get; set; }
    
        public virtual ALERT ALERT { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
