//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeYak
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOTEUP_VIEW
    {
        public string USERNAME_VOTER { get; set; }
        public decimal POST_ID { get; set; }
        public string DETAILS { get; set; }
        public Nullable<decimal> Total_Up_Votes { get; set; }
    }
}
